apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: dsattach
  namespace: kube-system
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: dsattach
    spec:
      containers:
      - image: registry.ng.bluemix.net/jeffpx/armada-block-volume-attacher #image name which should be avilable within cluster
        imagePullPolicy: Always
        name: container-name # name of the container inside POD
        securityContext:
          privileged: true
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
          - mountPath: /run/systemd
            name: sysd-run
          - mountPath: /host/etc
            name: host-etc
          - mountPath: /host/lib
            name: host-lib
          - mountPath: /host/var/log
            name: host-var-log
      volumes:
        - name: sysd-run
          hostPath:
            path: /run/systemd
        - name: host-etc
          hostPath:
            path: /etc/
        - name: host-lib
          hostPath:
            path: /lib/
        - name: host-var-log
          hostPath:
            path: /var/log
